services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/nextjs-frontend.Dockerfile
    depends_on:
      - web-backend-server
    restart: unless-stopped
    container_name: nextjs-frontend
    hostname: nextjs-frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - fusihub

  web-backend-server:
    build:
      context: .
      dockerfile: ./docker/web-backend-server.Dockerfile
    restart: unless-stopped
    container_name: web-backend-server
    hostname: web-backend-server
    ports:
      - "127.0.0.1:8888:8888"
    networks:
      - fusihub

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=Asia/Saigon
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    network_mode: host

networks:
  fusihub:
