# --> (Example) Expose an external service using Traefik...
http:
  routers:
    web-backend-server:
      rule: "Host(`local.fusihub.com`) && PathPrefix(`/api`)"
      service: web-backend-server #
      priority: 10
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: cloudflare
    nextjs-frontend:
      rule: "Host(`local.fusihub.com`)"
      service: nextjs-frontend #
      priority: 1
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: cloudflare

  services:
    web-backend-server:
      loadBalancer:
        servers:
          - url: "http://localhost:8888"
        passHostHeader: true

    nextjs-frontend:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"
        passHostHeader: true
