---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
 level: ERROR

# accesslog: {}

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  cloudflare:
    acme:
      email: ${CF_EMAIL}
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare  # <-- (Optional) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# serversTransport:
#   insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false 
    # network: frontend
  file:
    directory: /etc/traefik
    watch: true
